FROM node:16-alpine as builder
# Set the working directory to /app inside the container
WORKDIR /app
# Copy app files
# Install dependencies (npm ci makes sure the exact versions in the lockfile gets installed)
ENV REACT_APP_API_PATH /api
ENV WATCHPACK_POLLING true
RUN npm install 
COPY . .

expose 3000
CMD ["npm", "start"]
