version: "3.9"
services:
  app:
    build: .
    container_name: app
    ports:
      - "5000:5000"
    environment:
      - FLASK_DEBUG=true
      - API_KEY=c65i50aad3i9pn79r35g
      - DATABASE_PASSWORD=
      - DATABASE_NAME=trademanager
      - DATABASE_USER=root
      - DATABASE_HOST=db
    links:
      - db
  db:
    image: mysql
    container_name: db
    command: mysqld --authentication_policy=mysql_native_password
    ports: 
      - "3307:3306"
    restart: always
    environment:
      - MYSQL_DATABASE=trademanager
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    volumes:
      - /var/lib/mysql 
