version: "3.9"
services:
  db:
    image: mysql:latest
    container_name: db
    ports: 
      - "3305:3306"
    expose:
      - "3305"
        # DATABASE_HOST ENV VARIABLE MUST BE "db"
    env_file:
      - .env
    volumes:
      - ./.mysql-data/db:/var/lib/mysql 
    restart: always
  app:
    container_name: app
    build: 
      context: backend
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - .env
    links:
      - db
    # HOT RELOAD DEV ONLY
    volumes:
      - './backend:/app'
  frontend:
    container_name: frontend
    restart: always
    build:
      context: frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_PATH=${REACT_APP_API_PATH}
    #HOT RELOADING, DEV ONLY
    stdin_open: true
    volumes:
      - ./frontend:/app:delegated
  nginx:
    container_name: nginx
    build: 
      context: "./nginx"
      dockerfile: Dockerfile
    ports: 
      - "80:80"
    links: 
      - app
      - frontend
    restart: always
