version: "3.9"
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: app
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - .env
    links:
      - db
  db:
    image: mysql
    container_name: db
    command: mysqld --authentication_policy=mysql_native_password
    ports: 
      - "3307:3306"
    env_file:
      - .env
    volumes:
      - /var/lib/mysql 
  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: Dockerfile.client
    ports:
      - "3000:80"
