"""empty message

Revision ID: 11487d8e249a
Revises: 
Create Date: 2023-12-05 18:42:21.667314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11487d8e249a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.drop_index('value')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.create_index('value', ['value'], unique=False)

    # ### end Alembic commands ###
